from .auth_view import *
from .admin_view import *
from .doctors_view import *
from .patients_view import *
from .medistore_view import *
from .users_view import *
from .home_view import *
from .category_view import *
from .appointments_view import *
from .reports_view import *
from .availability_view import *
